version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "8001:8001"  
      - "8002:8002"  
      - "8003:8003"  
    environment:
      - NODE_ENV=development
    command: npx nodemon index.ts
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: